### ISSUE TITLE
Need to manually delete the mix.lock file before building new dependencies

### ISSUE THREAD

**Issue by nickjj** [nickjj/docker-web-framework-examples#1]
After adding new dependencies to your `mix.exs` file you need to run `mix deps.get` which means you'll want to run `docker-compose up --build`.

This example app has a `docker-entrypoint.sh` script that has this snippet:

```sh
if [ ! -f "/app/mix.lock" ]; then
    mix deps.get
fi
```

This prevents `mix deps.get` from running automatically if a `mix.lock` file exists. I originally did this because having `mix deps.get` run every time you start the container is a little annoying.

However, when you don't have a `mix.lock` file, it will get ran. Combine that with needing to run `mix deps.get` to install new dependencies then we need to delete the `mix.lock` file before running a `docker-compose build web`.

Now you might thinking "but why?". It's because the `mix.lock` created at build time will get overridden at run-time due to the app volume mount, so you end up with an outdated `mix.lock` file.

One possible solution would be to copy the `mix.lock` file to a different directory in the `Dockerfile` then in the `docker-entrypoint.sh` file we can compare the built `mix.lock` file (which ran at build time) vs the `mix.lock` file that's currently volume mounted in at runtime.

If the files are different, or there's no `mix.lock` file then `mix deps.get` command should be ran, otherwise it would get skipped (at runtime).

There's probably a more elegant solution to this, but I'm still new to Elixir and it hasn't bothered me too much in development yet. Would definitely appreciate help if you have any ideas!

**Comment by brentjanderson** [comment]
I would suggest rebuilding the container when changing dependencies. Dependency changes are relatively infrequent, and the mix.lock file is integral to ensuring you get consistent builds. By re-generating mix.lock each time you build the container, you run the risk of the software breaking since the versions aren't pinned, and that seems a much bigger problem than the inconvenience of rebuilding the container when you change your deps.

**Comment by nickjj** [comment]
Here's a more clear explanation of the problem:

1. You have an existing `mix.exs` and `mix.lock` file in your app's source code.
2. You update your `mix.exs` file to add a new dependency
3. You run `docker-compose build` to build the new deps into the image
4. A new `mix.lock` file is created inside of the image
5. You start your app with `docker-compose up`
6. You use a volume bind mount to load your source code from disk into the container
7. Mix explodes because your old `mix.lock` overrides the built `mix.lock`

```sh
if [ ! -f "/app/mix.lock" ]; then
    mix deps.get
fi
```

The above hack addresses that by giving you an ability to delete the `mix.lock` file on your local app's source code and now mix will generate a new one -- but as we know, this is a bad idea.

I was just working on a new workaround that never destroys the lock file. It looks like this so far:

##### Dockerfile

```Dockerfile
# Added && cp mix.lock /elixir to copy the lock file to an unmounted directory.
RUN mix local.hex --force && mix local.rebar --force \
    && mix deps.get && mix deps.compile && cp mix.lock /elixir
```

##### docker-entrypoint.sh

```sh
#!/bin/sh

set -e

built_lock_file="/elixir/mix.lock"
current_lock_file="/app/mix.lock"

function cp_built_lock_file() {
    cp "${built_lock_file}" "${current_lock_file}"
}

if [ -f "${current_lock_file}" ]; then
    if [ diff "${built_lock_file}" "${current_lock_file}" != "" ]; then
        cp_built_lock_file
    fi
else
    cp_built_lock_file
fi

exec "$@"
```

So far it's passing all tests I've thrown at it.

- If no `mix.lock` exists in your app's source code, it copies it from the built one from the image
- If a mismatched `mix.lock` exists in your app's source code, it copies it from the built one from the image
- If the volume mounted `mix.lock` matches the built one, then nothing happens
- If no volume mount is used, it skips everything and things work as planned

In all 4 cases, the app server starts without running `mix deps.get` an extra time.

**Comment by nickjj** [comment]
Just pushed this fix to master. If anyone knows of a better way, or noticed this introduced an issue, please re-open this.

**Comment by nickjj** [comment]
Here's an interesting turn of events.

In the `mix.exs` file I've already customized both the `build_path` and `deps_path` to output their files in the `/elixir` directory. This prevented dependencies from leaking out to your volumes on the Docker host.

But I just noticed there's also a `lockfile` path that you can set. Using this tactic you could have the `mix.lock` file get read and written to the `/elixir` folder which would avoid having to do everything included in this issue to work around the issue.

However, the one concern I have with this is, it would mean your working source directory would never have a `mix.lock` present. Technically this would be fine in terms of it working, but this might throw a lot of people off to never see a `mix.lock` file.

**Edit**: Just thinking out loud here, I won't implement this because not having a lock file in your source directory is a deal breaker.

**Comment by joustava** [comment]
@nickjj when you'd remove the lock file from your working source dir, wouldn't that defeat the purpose of having it in the source: repeatable builds?

**Comment by nickjj** [comment]
@joustava That file is machine generated. It would be restored from inside the built image when you run the container.

**Comment by joustava** [comment]
Yes sure. But you voiced a concern in your previous comment that changes to
the lock file will not be reflected in a development source tree. So even
if I generate it, and then push my code, any other Dev wouldn't see the
lock file (or changes to it) and the other Dev would possibly create a
build with a different dependency tree if eg one dependency has been
updated in the meantime. So I'd just leave the docker-entrypoint.sh as is.
But I might be just missing a point here though.

**Comment by nickjj** [comment]
Oh yeah, I scratched that idea completely.

Right now, the first implementation is in place, where you do end up with a lock file in your source directory.
