### ISSUE TITLE
Adding in a Laravel example, any takers?

### ISSUE THREAD

**Issue by nickjj** [nickjj/docker-web-framework-examples#2]
I don't use Laravel on a regular basis but I know it's really popular.

If anyone wants to open a PR for this, that would be great.

Before doing so, please glance through https://github.com/nickjj/docker-web-framework-examples/blob/master/CONTRIBUTING.md

**Comment by roc41d** [comment]
i will like to work on this :)

**Comment by nickjj** [comment]
If you need to ask any questions about the process, let me know here.

**Comment by roc41d** [comment]
ok
