### ISSUE TITLE
no need to install yarn

### ISSUE THREAD

**Issue by enjunear** [nickjj/docker-web-framework-examples#5]
The node image comes with yarn preinstalled.

**Comment by nickjj** [comment]
That is true but the 9.7 version of Node (the version being used in the Webpack example) installs a very old version of Yarn.

**Comment by beardedeagle** [comment]
I explicitly compile the latest version of node and leave out yarn in my multistage images. That's what I'd recommend if all the examples you are using don't need yarn.

**Comment by nickjj** [comment]
The last time I checked, I couldn't get webpack to work with the latest node version and both example apps (webpack and phoenix since phoenix is using webpack) depend on using yarn.

**Comment by enjunear** [comment]
Interesting points.

So this isn't really an "issue" per se, but more of a discussion. I didn't know the preinstalled yarn was old. At this moment, according to [nodejs/docker-node](https://github.com/nodejs/docker-node/blob/e3ec2111af089e31321e76641697e154b3b6a6c3/8/jessie/Dockerfile), the yarn version included is v1.6.0.

Because this isn't a real issue, I'll close it. But good discussion.

**Comment by nickjj** [comment]
The 9.7 and 9.11 tags use yarn 1.5.1. It can be seen at https://github.com/nodejs/docker-node/blob/e3ec2111af089e31321e76641697e154b3b6a6c3/9/alpine/Dockerfile#L49.
