### ISSUE TITLE
Version in "./docker-compose.yml" is Unsupported

### ISSUE THREAD

**Issue by garland** [nickjj/docker-web-framework-examples#6]
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

The remedy is to simply put "3" as the version instead of "3.3" etc

**Comment by nickjj** [comment]
Hi,

It sounds like you're using an older version of Docker Compose that doesn't support 3.3. Dropping down to 3 is fine if you need to.
