### ISSUE TITLE
Create New Setup for Phoenix 1.3.3

### ISSUE THREAD

**Issue by garland** [nickjj/docker-web-framework-examples#7]
Would it be possible for you to create a new configuration for the new Phoenix 1.3.3 release? I tried adjusting a few things here and there but couldn't get it to work for 1.3.3 - it seems like there is considerable directory changes in 1.3.3, it would be nice to update this for the new release if you have the time.

**Comment by nickjj** [comment]
Hi,

1.3.2 to 1.3.3 has no changes when it comes to directory structure. You can see what was changed here https://github.com/phoenixframework/phoenix/blob/v1.3/CHANGELOG.md#133-2018-06-15.

Replacing 1.3.2 to 1.3.3 in the `mix.exs` file and then running `docker-compose up --build` should be enough. Nothing changed in terms of the files being generated.

**Comment by nickjj** [comment]
Closing this. When 1.4 is released I will certainly update this repo for it.
